baseURL = "https://silentsilas.com/"
languageCode = "en-us"
title = "Silence Speaks"
disablePathToLower = false
paginate = 8
enableRobotsTXT = true
relativeURLs = true
# googleAnalytics = "UA-62812844-1"

[params]
    description = ""

[Author]
	name = "Silent Silas"
	email = "me@silentsilas.com"
	github = "Poeticode"

[taxonomies]
tag = "tags"
category = "categories"
series = "series"
